export const WEBSOCKET_CMD = {
    TEMPERATURE: 'GET_DASHBOARD_TEMPERATURE',
    HUMIDITY: 'GET_HUMIDITY_DATA',
    LOOKING_CULTIVATION: 'LOOKING_CULTIVATION',
    GET_CLIMATIC_DATA: 'getClimaticData'
};